In [2]:
import  numpy as np
import  pandas as pd
import  matplotlib.pyplot as plt
import  seaborn as sns
from sklearn.preprocessing import LabelEncoder,StandardScaler,MinMaxScaler,PowerTransformer,OrdinalEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer  
from sklearn.model_selection import train_test_split

In [3]:
from sklearn import set_config
set_config(transform_output='pandas')

### load data

In [5]:
df_ren = pd.read_csv("renamed_data.csv")

In [7]:
df_ren.columns

Index(['rider_id', 'age', 'ratings', 'restaurant_latitude',
       'restaurant_longitude', 'delivery_latitude', 'delivery_longitude',
       'order_date', 'weather_conditions', 'traffic', 'vehicle_condition',
       'type_of_order', 'type_of_vehicle', 'multiple_deliveries', 'festival',
       'city_type', 'time_taken', 'city_name', 'distance', 'order_day',
       'order_month', 'order_year', 'order_day_of_week', 'is_weekend',
       'order_time_hour', 'order_time_of_day', 'weather',
       'time_taken_transformed'],
      dtype='str')

In [ ]:
import data_clean_utils

In [25]:
df_ren

,rider_id,age,ratings,restaurant_latitude,restaurant_longitude,delivery_latitude,delivery_longitude,order_date,weather_conditions,traffic,...,distance,order_day,order_month,order_year,order_day_of_week,is_weekend,order_time_hour,order_time_of_day,weather,time_taken_transformed
0,INDORES02DEL01,23.0,4.5,22.651847,75.881991,22.721847,75.951991,2022-03-18,Stormy,low,...,10.590448,18,3,2022,friday,0,22.0,night,stormy,-1.007612
1,MYSRES20DEL01,39.0,4.3,12.337978,76.616792,12.377978,76.656792,2022-03-17,Cloudy,medium,...,6.217689,17,3,2022,thursday,0,15.0,afternoon,cloudy,0.775261
2,MYSRES07DEL02,37.0,4.8,12.325461,76.632278,12.375461,76.682278,2022-03-03,Windy,low,...,7.772220,3,3,2022,thursday,0,23.0,night,windy,-0.606936
3,SURRES12DEL03,30.0,4.8,21.183434,72.814492,21.213434,72.844492,2022-03-05,Sandstorms,medium,...,4.560784,5,3,2022,saturday,1,17.0,evening,sandstorms,0.193567
4,VADRES13DEL02,29.0,4.6,22.310237,73.158921,22.360237,73.208921,2022-03-11,Cloudy,jam,...,7.573470,11,3,2022,friday,0,21.0,night,cloudy,0.088418
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36420,CHENRES12DEL01,39.0,4.7,12.972793,80.249982,13.042793,80.319982,2022-03-02,Stormy,low,...,10.867421,2,3,2022,wednesday,0,22.0,night,stormy,0.193567
36421,JAPRES01DEL01,37.0,4.8,26.905190,75.810753,26.945190,75.850753,2022-03-15,Stormy,medium,...,5.958966,15,3,2022,tuesday,0,15.0,afternoon,stormy,0.088418
36422,RANCHIRES08DEL02,30.0,4.2,23.353783,85.326967,23.483783,85.456967,2022-03-04,Stormy,jam,...,19.619012,4,3,2022,friday,0,21.0,night,stormy,1.124478
36423,INDORES08DEL03,NaN,NaN,22.725748,75.898497,22.755747,75.928497,2022-03-21,Stormy,jam,...,5057.312542,21,3,2022,monday,0,NaN,after_midnight,stormy,-1.151421
36424,KOCRES010DEL01,38.0,4.9,10.035573,76.336958,10.045573,76.346958,2022-02-15,Fog,high,...,1.560538,15,2,2022,tuesday,0,11.0,morning,fog,1.207768

In [14]:
renamed = data_clean_utils.perform_data_cleaning(df_ren)
print(renamed.columns.tolist())
print(renamed.dtypes)

KeyError: 'order_picked_time'

In [15]:
columns_to_drop = ['Order_Date','Time_Orderd','Delivery_person_ID']
df_ren.drop(columns=columns_to_drop, inplace=True)

KeyError: "['Order_Date', 'Time_Orderd', 'Delivery_person_ID'] not found in axis"

In [16]:
df_ren

,rider_id,age,ratings,restaurant_latitude,restaurant_longitude,delivery_latitude,delivery_longitude,order_date,weather_conditions,traffic,...,distance,order_day,order_month,order_year,order_day_of_week,is_weekend,order_time_hour,order_time_of_day,weather,time_taken_transformed
0,INDORES02DEL01,23.0,4.5,22.651847,75.881991,22.721847,75.951991,2022-03-18,Stormy,low,...,10.590448,18,3,2022,friday,0,22.0,night,stormy,-1.007612
1,MYSRES20DEL01,39.0,4.3,12.337978,76.616792,12.377978,76.656792,2022-03-17,Cloudy,medium,...,6.217689,17,3,2022,thursday,0,15.0,afternoon,cloudy,0.775261
2,MYSRES07DEL02,37.0,4.8,12.325461,76.632278,12.375461,76.682278,2022-03-03,Windy,low,...,7.772220,3,3,2022,thursday,0,23.0,night,windy,-0.606936
3,SURRES12DEL03,30.0,4.8,21.183434,72.814492,21.213434,72.844492,2022-03-05,Sandstorms,medium,...,4.560784,5,3,2022,saturday,1,17.0,evening,sandstorms,0.193567
4,VADRES13DEL02,29.0,4.6,22.310237,73.158921,22.360237,73.208921,2022-03-11,Cloudy,jam,...,7.573470,11,3,2022,friday,0,21.0,night,cloudy,0.088418
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36420,CHENRES12DEL01,39.0,4.7,12.972793,80.249982,13.042793,80.319982,2022-03-02,Stormy,low,...,10.867421,2,3,2022,wednesday,0,22.0,night,stormy,0.193567
36421,JAPRES01DEL01,37.0,4.8,26.905190,75.810753,26.945190,75.850753,2022-03-15,Stormy,medium,...,5.958966,15,3,2022,tuesday,0,15.0,afternoon,stormy,0.088418
36422,RANCHIRES08DEL02,30.0,4.2,23.353783,85.326967,23.483783,85.456967,2022-03-04,Stormy,jam,...,19.619012,4,3,2022,friday,0,21.0,night,stormy,1.124478
36423,INDORES08DEL03,NaN,NaN,22.725748,75.898497,22.755747,75.928497,2022-03-21,Stormy,jam,...,5057.312542,21,3,2022,monday,0,NaN,after_midnight,stormy,-1.151421
36424,KOCRES010DEL01,38.0,4.9,10.035573,76.336958,10.045573,76.346958,2022-02-15,Fog,high,...,1.560538,15,2,2022,tuesday,0,11.0,morning,fog,1.207768

In [17]:
df_ren.isna().sum()

rider_id                     0
age                       1501
ratings                   1547
restaurant_latitude          0
restaurant_longitude         0
delivery_latitude            0
delivery_longitude           0
order_date                   0
weather_conditions         451
traffic                    440
vehicle_condition            0
type_of_order                0
type_of_vehicle              0
multiple_deliveries        790
festival                   192
city_type                  955
time_taken                   0
city_name                    0
distance                     0
order_day                    0
order_month                  0
order_year                   0
order_day_of_week            0
is_weekend                   0
order_time_hour           1359
order_time_of_day            0
weather                    451
time_taken_transformed       0
dtype: int64

In [ ]:
df.dtypes

In [ ]:
location_columns = df.columns[3:8].tolist()
location_columns

In [ ]:
location_subset = df.loc[:, location_columns]
location_subset

In [18]:
# %%
%load_ext autoreload
%autoreload 2

import numpy as np
import pandas as pd
import data_clean_utils

In [23]:
df_cleaned = data_clean_utils.data_cleaning(df_ren)
df_cleaned.head()

KeyError: 'order_picked_time'

In [ ]:
df_cleaned_1 = data_clean_utils.perform_data_cleaning(df)
df_cleaned_1.head()

In [ ]:
data_clean_utils.perform_data_cleaning(df)

In [ ]:
def calculate_haversine_distance(df):
    location_columns = location_subset.columns.tolist()

    lat1 = df[location_columns[0]]
    lon1 = df[location_columns[1]]
    lat2 = df[location_columns[2]]
    lon2 = df[location_columns[3]]

    lon1, lat1, lon2, lat2 = map(
        np.radians, [lon1, lat1, lon2, lat2]
    )

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = (
        np.sin(dlat / 2.0) ** 2
        + np.cos(lat1) * np.cos(lat2)
        * np.sin(dlon / 2.0) ** 2
    )

    c = 2 * np.arcsin(np.sqrt(a))
    distance = 6371 * c

    return (
        df.assign(
            distance=distance
        )
    )

In [ ]:
# Apply the function to create the new 'distance' column
df = calculate_haversine_distance(df)

# Check the new column along with your coordinates
print(df[['restaurant_latitude', 'restaurant_longitude', 'delivery_latitude', 'delivery_longitude', 'distance']].head())